	# =========================
	# DATABASE (MySQL)
	# =========================
	spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
	
	spring.datasource.url=jdbc:mysql://localhost:3306/compare?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Africa/Cairo
	spring.datasource.username=root
	spring.datasource.password=AnubisArray130
	
	# =========================
	# JPA / HIBERNATE
	# =========================
	spring.jpa.hibernate.ddl-auto=update
	spring.jpa.show-sql=true
	
	# سيبها فاضية عشان Spring يحدد Dialect تلقائيًا
	spring.jpa.database-platform=
	
	spring.jpa.properties.hibernate.format_sql=true
	spring.jpa.properties.hibernate.jdbc.batch_size=5
	
	# =========================
	# H2 (لو مش هتستخدمه احذفه)
	# =========================
	spring.h2.console.enabled=false
	
	# =========================
	# MVC / ERRORS
	# =========================
	spring.mvc.throw-exception-if-no-handler-found=true
	spring.web.resources.add-mappings=false
	
	# =========================
	# JSON
	# =========================
	spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
	spring.jackson.time-zone=Africa/Cairo
	
	# =========================
	# SERVER
	# =========================
	server.port=8080
	
	# =========================
	# FILE UPLOAD
	# =========================
	spring.servlet.multipart.enabled=true
	spring.servlet.multipart.max-file-size=1000MB
	spring.servlet.multipart.max-request-size=1000MB
	
	# =========================
	# LOGGING
	# =========================
	spring.output.ansi.enabled=always
	spring.main.banner-mode=off
	
	# =========================
	# SPRING DEVTOOLS
	# =========================
	spring.devtools.restart.enabled=true
	
	# =========================
	# JASPER REPORTS
	# =========================
	net.sf.jasperreports.default.font.name=Arial
	net.sf.jasperreports.default.pdf.encoding=Identity-H
	net.sf.jasperreports.default.pdf.embedded=true